// ORDERS Action Constants
export const ADD_ORDER = 'ADD_ORDER';
export const ADD_ADD_ONS = 'ADD_ADD_ONS';
export const ADD_ORDER_ADDRESS = 'ADD_ORDER_ADDRESS';
export const REQUEST_COMPLETE = 'REQUEST_COMPLETE';
export const DELETE_ORDER = 'DELETE_ORDER';

// CLEANERS ACTION CONSTANTS
export const ADD_CLEANER_PROFILE = 'ADD_CLEANER_PROFILE';

// USERS Action Constants
export const LOGIN_WATCHER = 'LOGIN_WATCHER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT_WATCHER = 'LOGOUT_WATCHER';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const DELETE_TOKEN = 'DELETE_TOKEN';
export const LOGIN_CANCELLED = 'LOGIN_CANCELLED';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
