// ORDERS ACTION CONSTANTS
export const LOAD_ORDERS = 'LOAD_ORDERS';
export const LOAD_ORDERS_SUCCESS = 'LOAD_ORDERS_SUCCESS';
export const LOAD_ORDERS_FAIL = 'LOAD_ORDERS_FAIL';
export const POST_ORDER = 'POST_ORDER';
export const POST_ORDER_SUCCESS = 'POST_ORDER_SUCCESS';
export const POST_ORDER_FAIL = 'POST_ORDER_FAIL';

export const ADD_ORDER = 'ADD_ORDER';
export const ADD_ADD_ONS = 'ADD_ADD_ONS';
export const ADD_ORDER_ADDRESS = 'ADD_ORDER_ADDRESS';
export const REQUEST_COMPLETE = 'REQUEST_COMPLETE';
export const DELETE_ORDER = 'DELETE_ORDER';

// CLEANERS ACTION CONSTANTS
export const APPLY_CLEANER_WATCHER = 'APPLY_CLEANER_WATCHER';
export const ADD_CLEANER_PROFILE = 'ADD_CLEANER_PROFILE';
export const DELETE_CLEANER_PROFILE = 'DELETE_CLEANER_PROFILE';

// USERS ACTION CONSTANTS
export const LOGIN_WATCHER = 'LOGIN_WATCHER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_CANCELLED = 'LOGIN_CANCELLED';
export const LOGOUT_WATCHER = 'LOGOUT_WATCHER';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const SIGNUP_WATCHER = 'SIGNUP_WATCHER';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const SIGNUP_CANCELLED = 'SIGNUP_CANCELLED';
export const EDIT_PROFILE_WATCHER = 'EDITPROFILE_WATCHER';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const GET_PROFILE_WATCHER = 'GET_PROFILE_WATCHER';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
